In [1]:
# pandas is an open source Python library for data manipulations and analysis
    #  Scopes of Pandas 
        # ---> Data scientist
        # ---> Machine learning
        # ---> AI engineerig
        # ---> Data analyst...etc
# Pandas is fundamental for all sectors

In [2]:
# installation pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
# import pandas
import pandas as pd

In [5]:
# checking the pandas version
pd.__version__

'3.0.3'

In [6]:
# dataframe
    # the collection of the data is a dataframe

In [7]:
# Lession 1: Creating a dataframe

In [8]:
df = pd.DataFrame([11,22,33,44,55,66,77,88,99])

# Printing the provided dataframe

In [9]:
print(df)

    0
0  11
1  22
2  33
3  44
4  55
5  66
6  77
7  88
8  99

In [10]:
df = pd.DataFrame([11,22,33,44,55,66,77,88,99],columns = ['Col_Name'])

In [11]:
df

   Col_Name
0        11
1        22
2        33
3        44
4        55
5        66
6        77
7        88
8        99

In [12]:
# checking the type of df
print(type(df))

<class 'pandas.DataFrame'>

In [13]:
# Making new dataframe
data ={
    'Name':["Anil", "Sunil", "Pranil", "Unil", "Banmboo", "Hancy", "Hakim", "Fantus", "Binny", "Prajin"],
    'lName':["Shakya", "Prajapati", "Shrestha", "Pradhan", "Maharjan", "Shakya", "Pradhan", "Maharjan", "Tamang", "Chetri"],
    'Age':[34,36,35,46,34,36,35,46,23,43],
    'Field':["Frontend","UIUX","Backend","Graphics", "Data Scientist","UIUX","Backend","Graphics", "Data Scientist","Graphics"],
    'Salary':[100000,120000,200000,90000,100000,120000,200000,90000,100000,120000]
}

In [14]:
df = pd.DataFrame(data)
print(df)

      Name      lName  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [15]:
df

      Name      lName  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [16]:
print(type(df))

<class 'pandas.DataFrame'>

In [17]:
# Lesson 2
# Basics DataFrame Understanding

In [18]:
df.head() # top 5 data will be printed

      Name      lName  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000

In [19]:
df.head(2) # Top 2 data will be printed

    Name      lName  Age     Field  Salary
0   Anil     Shakya   34  Frontend  100000
1  Sunil  Prajapati   36      UIUX  120000

In [20]:
df.tail() # Last 5 data will be printed

     Name     lName  Age           Field  Salary
5   Hancy    Shakya   36            UIUX  120000
6   Hakim   Pradhan   35         Backend  200000
7  Fantus  Maharjan   46        Graphics   90000
8   Binny    Tamang   23  Data Scientist  100000
9  Prajin    Chetri   43        Graphics  120000

In [21]:
df.tail(2) # Last 2 data will be printed

     Name   lName  Age           Field  Salary
8   Binny  Tamang   23  Data Scientist  100000
9  Prajin  Chetri   43        Graphics  120000

In [22]:
# Rows and columns finding
df.shape

(10, 5)

In [23]:
df.columns

Index(['Name', 'lName', 'Age', 'Field', 'Salary'], dtype='str')

In [24]:
df.rename(columns = {'lName':'Last Name'})

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [25]:
df

      Name      lName  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [26]:
df.rename(columns = {'lName':'Last Name'},inplace = True) # change the col_name permanently

In [27]:
df

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [28]:
df.info() # Getting information of the data

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       10 non-null     str
 1   Last Name  10 non-null     str
 2   Age        10 non-null     int64
 3   Field      10 non-null     str
 4   Salary     10 non-null     int64
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [29]:
df.info

<bound method DataFrame.info of       Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000>

In [30]:
# describes the statistical summary information of the data
df.describe()

           Age         Salary
count  10.0000      10.000000
mean   36.8000  124000.000000
std     6.8443   41686.661869
min    23.0000   90000.000000
25%    34.2500  100000.000000
50%    35.5000  110000.000000
75%    41.2500  120000.000000
max    46.0000  200000.000000

In [31]:
# Now let's learn how the data is saved and load from the csv files

In [32]:
# Let's save the csv data
# Exports the data
df.to_csv('data.csv',index = False) # index = False basically doesn't send the index values

In [33]:
df

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [34]:
pd.read_csv('data.csv') # Loading data

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [35]:
load_data = pd.read_csv('data.csv')

In [36]:
load_data

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [37]:
# 4. Rows & Columns - Selections

In [38]:
df[['Last Name']]

   Last Name
0     Shakya
1  Prajapati
2   Shrestha
3    Pradhan
4   Maharjan
5     Shakya
6    Pradhan
7   Maharjan
8     Tamang
9     Chetri

In [39]:
df[['Name','Last Name']] # Selecting the columns

      Name  Last Name
0     Anil     Shakya
1    Sunil  Prajapati
2   Pranil   Shrestha
3     Unil    Pradhan
4  Banmboo   Maharjan
5    Hancy     Shakya
6    Hakim    Pradhan
7   Fantus   Maharjan
8    Binny     Tamang
9   Prajin     Chetri

In [40]:
# loc - Lable based index
# selects the rows
df.loc[df.Name =='Anil'] # Selecting Row in index based

   Name Last Name  Age     Field  Salary
0  Anil    Shakya   34  Frontend  100000

In [41]:
df.loc[0]

Name             Anil
Last Name      Shakya
Age                34
Field        Frontend
Salary         100000
Name: 0, dtype: object

In [42]:
df.loc[(df.Name == 'Anil') & (df.Salary >= 50000)] # Giving conditions

   Name Last Name  Age     Field  Salary
0  Anil    Shakya   34  Frontend  100000

In [43]:
# iloc - index-value based 

df.iloc[3]

Name             Unil
Last Name     Pradhan
Age                46
Field        Graphics
Salary          90000
Name: 3, dtype: object

In [44]:
df.iloc[2:5] # [start:stop] excludes in iloc

      Name Last Name  Age           Field  Salary
2   Pranil  Shrestha   35         Backend  200000
3     Unil   Pradhan   46        Graphics   90000
4  Banmboo  Maharjan   34  Data Scientist  100000

In [45]:
df.loc[0:4]  # [start:stop] includes in loc

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000

In [46]:
df['Age'] > 30 # Provides the bool value

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8    False
9     True
Name: Age, dtype: bool

In [47]:
df[df['Age']>30] # Provide all the detailed data

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
9   Prajin     Chetri   43        Graphics  120000

In [48]:
df['Salary'] >= 100000

0     True
1     True
2     True
3    False
4     True
5     True
6     True
7    False
8     True
9     True
Name: Salary, dtype: bool

In [49]:
df[df['Salary'] >= 100000] # shows all the dataframe of the table

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [50]:
df[(df['Salary'] >= 100000) & (df['Age'] <= 30 )] # df[(condition1) & (condition2)] 
# Salary that is greater than 100000 & Age < 30

    Name Last Name  Age           Field  Salary
8  Binny    Tamang   23  Data Scientist  100000

In [51]:
df.where(df['Salary'] >= 100000) # data that doesn't fits the condition is displayed as NaN

      Name  Last Name   Age           Field    Salary
0     Anil     Shakya  34.0        Frontend  100000.0
1    Sunil  Prajapati  36.0            UIUX  120000.0
2   Pranil   Shrestha  35.0         Backend  200000.0
3      NaN        NaN   NaN             NaN       NaN
4  Banmboo   Maharjan  34.0  Data Scientist  100000.0
5    Hancy     Shakya  36.0            UIUX  120000.0
6    Hakim    Pradhan  35.0         Backend  200000.0
7      NaN        NaN   NaN             NaN       NaN
8    Binny     Tamang  23.0  Data Scientist  100000.0
9   Prajin     Chetri  43.0        Graphics  120000.0

In [52]:
df.where(df['Salary'] >= 100000, other = "Not Eligible") # other changed NaN to Not Eligible

           Name     Last Name           Age           Field        Salary
0          Anil        Shakya            34        Frontend        100000
1         Sunil     Prajapati            36            UIUX        120000
2        Pranil      Shrestha            35         Backend        200000
3  Not Eligible  Not Eligible  Not Eligible    Not Eligible  Not Eligible
4       Banmboo      Maharjan            34  Data Scientist        100000
5         Hancy        Shakya            36            UIUX        120000
6         Hakim       Pradhan            35         Backend        200000
7  Not Eligible  Not Eligible  Not Eligible    Not Eligible  Not Eligible
8         Binny        Tamang            23  Data Scientist        100000
9        Prajin        Chetri            43        Graphics        120000

In [53]:
# Lesson 6. Rows and Columns - Operations (Add, Update, Delete)

In [54]:
df

      Name  Last Name  Age           Field  Salary
0     Anil     Shakya   34        Frontend  100000
1    Sunil  Prajapati   36            UIUX  120000
2   Pranil   Shrestha   35         Backend  200000
3     Unil    Pradhan   46        Graphics   90000
4  Banmboo   Maharjan   34  Data Scientist  100000
5    Hancy     Shakya   36            UIUX  120000
6    Hakim    Pradhan   35         Backend  200000
7   Fantus   Maharjan   46        Graphics   90000
8    Binny     Tamang   23  Data Scientist  100000
9   Prajin     Chetri   43        Graphics  120000

In [55]:
# Add new column
df['Location'] = ['Kathmandu','Bhaktapur','Pokhara','Lalitpur','Sanga','Surkhet','Panauti','Jaulakhel','Dhulikhel','Basantapur']

In [56]:
df

      Name  Last Name  Age           Field  Salary    Location
0     Anil     Shakya   34        Frontend  100000   Kathmandu
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur
2   Pranil   Shrestha   35         Backend  200000     Pokhara
3     Unil    Pradhan   46        Graphics   90000    Lalitpur
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga
5    Hancy     Shakya   36            UIUX  120000     Surkhet
6    Hakim    Pradhan   35         Backend  200000     Panauti
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel
9   Prajin     Chetri   43        Graphics  120000  Basantapur

In [57]:
df.to_csv('data1.csv', index =False)

In [58]:
df['Bonus'] = 0.25 * df['Salary']

In [59]:
df

      Name  Last Name  Age           Field  Salary    Location    Bonus
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3     Unil    Pradhan   46        Graphics   90000    Lalitpur  22500.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0

In [60]:
df.to_csv('new_data.csv', index = False)

In [61]:
df

      Name  Last Name  Age           Field  Salary    Location    Bonus
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3     Unil    Pradhan   46        Graphics   90000    Lalitpur  22500.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0

In [62]:
# Adding rows

df.loc[len(df)] = ['Sujin','Tandukar',22,'Backend',40000,'Thimi',2000]

In [63]:
df

       Name  Last Name  Age           Field  Salary    Location    Bonus
0      Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1     Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2    Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3      Unil    Pradhan   46        Graphics   90000    Lalitpur  22500.0
4   Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5     Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6     Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7    Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8     Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9    Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
10    Sujin   Tandukar   22         Backend   40000       Thimi   2000.0

In [64]:
len(df)

11

In [65]:
# Update the value by using index name
df.loc[3,'Salary'] = 150000

In [66]:
df

       Name  Last Name  Age           Field  Salary    Location    Bonus
0      Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1     Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2    Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3      Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
4   Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5     Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6     Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7    Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8     Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9    Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
10    Sujin   Tandukar   22         Backend   40000       Thimi   2000.0

In [67]:
# Update the value by using column value
df.loc[df.Name =='Sujin','Salary'] = 150000

In [68]:
df

       Name  Last Name  Age           Field  Salary    Location    Bonus
0      Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1     Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2    Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3      Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
4   Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5     Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6     Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7    Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8     Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9    Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
10    Sujin   Tandukar   22         Backend  150000       Thimi   2000.0

In [69]:
# Delete value - Rows and columns values
df.drop(df[df.Name == "Sujin"].index, inplace = True) # drop row, axis = 0

In [70]:
df.drop('Bonus',axis = 1)

      Name  Last Name  Age           Field  Salary    Location
0     Anil     Shakya   34        Frontend  100000   Kathmandu
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur
2   Pranil   Shrestha   35         Backend  200000     Pokhara
3     Unil    Pradhan   46        Graphics  150000    Lalitpur
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga
5    Hancy     Shakya   36            UIUX  120000     Surkhet
6    Hakim    Pradhan   35         Backend  200000     Panauti
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel
9   Prajin     Chetri   43        Graphics  120000  Basantapur

In [71]:
df

      Name  Last Name  Age           Field  Salary    Location    Bonus
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0

In [72]:
df.drop(['Bonus','Age'], axis = 1) # Deletes the  Multiple columns

      Name  Last Name           Field  Salary    Location
0     Anil     Shakya        Frontend  100000   Kathmandu
1    Sunil  Prajapati            UIUX  120000   Bhaktapur
2   Pranil   Shrestha         Backend  200000     Pokhara
3     Unil    Pradhan        Graphics  150000    Lalitpur
4  Banmboo   Maharjan  Data Scientist  100000       Sanga
5    Hancy     Shakya            UIUX  120000     Surkhet
6    Hakim    Pradhan         Backend  200000     Panauti
7   Fantus   Maharjan        Graphics   90000   Jaulakhel
8    Binny     Tamang  Data Scientist  100000   Dhulikhel
9   Prajin     Chetri        Graphics  120000  Basantapur

In [73]:
df

      Name  Last Name  Age           Field  Salary    Location    Bonus
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0

In [74]:
df.drop(1,axis = 0) # 1	Sunil	Prajapati is deleted

      Name Last Name  Age           Field  Salary    Location    Bonus
0     Anil    Shakya   34        Frontend  100000   Kathmandu  25000.0
2   Pranil  Shrestha   35         Backend  200000     Pokhara  50000.0
3     Unil   Pradhan   46        Graphics  150000    Lalitpur  22500.0
4  Banmboo  Maharjan   34  Data Scientist  100000       Sanga  25000.0
5    Hancy    Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim   Pradhan   35         Backend  200000     Panauti  50000.0
7   Fantus  Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8    Binny    Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9   Prajin    Chetri   43        Graphics  120000  Basantapur  30000.0

In [75]:
df

      Name  Last Name  Age           Field  Salary    Location    Bonus
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0

In [76]:
# Sort by value - 
df.sort_values('Salary')

      Name  Last Name  Age           Field  Salary    Location    Bonus
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0

In [77]:
df.sort_values('Bonus')

      Name  Last Name  Age           Field  Salary    Location    Bonus
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0

In [78]:
df.sort_values("Age") #Ascending order

      Name  Last Name  Age           Field  Salary    Location    Bonus
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0

In [79]:
df.sort_values("Age", ascending = False) # for descending order

      Name  Last Name  Age           Field  Salary    Location    Bonus
7   Fantus   Maharjan   46        Graphics   90000   Jaulakhel  22500.0
3     Unil    Pradhan   46        Graphics  150000    Lalitpur  22500.0
9   Prajin     Chetri   43        Graphics  120000  Basantapur  30000.0
1    Sunil  Prajapati   36            UIUX  120000   Bhaktapur  30000.0
5    Hancy     Shakya   36            UIUX  120000     Surkhet  30000.0
6    Hakim    Pradhan   35         Backend  200000     Panauti  50000.0
2   Pranil   Shrestha   35         Backend  200000     Pokhara  50000.0
0     Anil     Shakya   34        Frontend  100000   Kathmandu  25000.0
4  Banmboo   Maharjan   34  Data Scientist  100000       Sanga  25000.0
8    Binny     Tamang   23  Data Scientist  100000   Dhulikhel  25000.0

In [80]:
# Lesson 7: Working with Date Values

In [81]:
df['DOJ'] = ['2022-07-04','2024-03-14','2023-04-11','2022-01-03','2025-11-04','2023-11-11','2026-09-14','2023-07-26','2023-07-14','2022-08-28',]

In [82]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28

In [83]:
df['DOJ'].dtype # <StringDtype(storage='python', na_value=nan)>

In [84]:
df['DOJ']= pd.to_datetime(df['DOJ'])

In [85]:
df['DOJ'].dtype #dtype('<M8[us]') means date and time in pandas

dtype('<M8[us]')

In [86]:
df1 = df

In [87]:
df1

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28

In [88]:
df1['DOJ2'] = ['07-04-2022','03-14-2024','04-11-2023','01-03-2022','11-04-2025','11-11-2023','09-14-2026','07-26-2023','07-14-2023','08-28-2022']

In [89]:
df1

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ,DOJ2
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04,07-04-2022
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14,03-14-2024
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11,04-11-2023
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03,01-03-2022
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04,11-04-2025
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11,11-11-2023
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14,09-14-2026
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26,07-26-2023
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14,07-14-2023
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28,08-28-2022

In [90]:
df1['DOJ2'].dtype

In [92]:
df1['DOJ2']= pd.to_datetime(df1['DOJ2'])

In [93]:
df1

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ,DOJ2
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28,2022-08-28

In [95]:
df1['DOJ2']= pd.to_datetime(df1['DOJ2'],format = '%d-%m-%Y')

In [96]:
df1

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ,DOJ2
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28,2022-08-28

In [97]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [98]:
df = df.drop('DOJ2',axis = 1)

In [99]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28

In [100]:
df['DOJ'].dt.year # gives all the year values

0    2022
1    2024
2    2023
3    2022
4    2025
5    2023
6    2026
7    2023
8    2023
9    2022
Name: DOJ, dtype: int32

In [101]:
df['DOJ'].dt.month # gives all joined month values

0     7
1     3
2     4
3     1
4    11
5    11
6     9
7     7
8     7
9     8
Name: DOJ, dtype: int32

In [102]:
df['DOJ'].dt.day # gives all joined date values

0     4
1    14
2    11
3     3
4     4
5    11
6    14
7    26
8    14
9    28
Name: DOJ, dtype: int32

In [105]:
df['DOJ'].dt.day_name() # gives all joined day values

0       Monday
1     Thursday
2      Tuesday
3       Monday
4      Tuesday
5     Saturday
6       Monday
7    Wednesday
8       Friday
9       Sunday
Name: DOJ, dtype: str

In [107]:
# 
df['Month'] = df['DOJ'].dt.month

In [108]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ,Month
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04,7
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14,3
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11,4
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03,1
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04,11
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11,11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14,9
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26,7
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14,7
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28,8

In [109]:
df['Date'] = df['DOJ'].dt.date

In [110]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ,Month,Date
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04,7,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14,3,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11,4,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03,1,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04,11,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11,11,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14,9,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26,7,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14,7,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28,8,2022-08-28

In [113]:
df.drop('Date',axis = 1, inplace = True)

In [114]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ,Month
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04,7
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14,3
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11,4
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03,1
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04,11
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11,11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14,9
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26,7
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14,7
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28,8

In [115]:
df.drop('Month',axis = 1,inplace = True)

In [116]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28

In [127]:
df['DOJ'] + pd.Timedelta(days = 90)

0   2022-10-02
1   2024-06-12
2   2023-07-10
3   2022-04-03
4   2026-02-02
5   2024-02-09
6   2026-12-13
7   2023-10-24
8   2023-10-12
9   2022-11-26
Name: DOJ, dtype: datetime64[us]

In [128]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,100000,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000,Basantapur,30000.0,2022-08-28

In [ ]:
# Lesson 8. Handling missing values

In [129]:
df.isnull()

    Name  Last Name    Age  Field  Salary  Location  Bonus    DOJ
0  False      False  False  False   False     False  False  False
1  False      False  False  False   False     False  False  False
2  False      False  False  False   False     False  False  False
3  False      False  False  False   False     False  False  False
4  False      False  False  False   False     False  False  False
5  False      False  False  False   False     False  False  False
6  False      False  False  False   False     False  False  False
7  False      False  False  False   False     False  False  False
8  False      False  False  False   False     False  False  False
9  False      False  False  False   False     False  False  False

In [131]:
import numpy as np

In [132]:
df.loc[df.Name == 'Binny', 'Salary']=np.nan

In [133]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000.0,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000.0,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000.0,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000.0,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000.0,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000.0,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000.0,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000.0,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,NaN,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000.0,Basantapur,30000.0,2022-08-28

In [135]:
df.isnull()

    Name  Last Name    Age  Field  Salary  Location  Bonus    DOJ
0  False      False  False  False   False     False  False  False
1  False      False  False  False   False     False  False  False
2  False      False  False  False   False     False  False  False
3  False      False  False  False   False     False  False  False
4  False      False  False  False   False     False  False  False
5  False      False  False  False   False     False  False  False
6  False      False  False  False   False     False  False  False
7  False      False  False  False   False     False  False  False
8  False      False  False  False    True     False  False  False
9  False      False  False  False   False     False  False  False

In [136]:
df.isnull().sum() # add all the null values

Name         0
Last Name    0
Age          0
Field        0
Salary       1
Location     0
Bonus        0
DOJ          0
dtype: int64

In [137]:
df.loc[df.Name == 'Binny', 'Salary']= 120500

In [138]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000.0,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000.0,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000.0,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000.0,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000.0,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000.0,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000.0,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000.0,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,120500.0,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000.0,Basantapur,30000.0,2022-08-28

In [139]:
# Lesson 9. Aggregation and Group By

In [142]:
df['Bonus'].value_counts()

Bonus
25000.0    3
30000.0    3
50000.0    2
22500.0    2
Name: count, dtype: int64

In [143]:
df[df['Bonus']==25000].value_counts() # Frequency of value

Name     Last Name  Age  Field           Salary    Location   Bonus    DOJ
Anil     Shakya     34   Frontend        100000.0  Kathmandu  25000.0  2022-07-04    1
Banmboo  Maharjan   34   Data Scientist  100000.0  Sanga      25000.0  2025-11-04    1
Binny    Tamang     23   Data Scientist  120500.0  Dhulikhel  25000.0  2023-07-14    1
Name: count, dtype: int64

In [144]:
df[df["Bonus"]==30000].value_counts()

Name    Last Name  Age  Field     Salary    Location    Bonus    DOJ
Sunil   Prajapati  36   UIUX      120000.0  Bhaktapur   30000.0  2024-03-14    1
Hancy   Shakya     36   UIUX      120000.0  Surkhet     30000.0  2023-11-11    1
Prajin  Chetri     43   Graphics  120000.0  Basantapur  30000.0  2022-08-28    1
Name: count, dtype: int64

In [146]:
df[df['Bonus']==50000].value_counts()

Name    Last Name  Age  Field    Salary    Location  Bonus    DOJ
Pranil  Shrestha   35   Backend  200000.0  Pokhara   50000.0  2023-04-11    1
Hakim   Pradhan    35   Backend  200000.0  Panauti   50000.0  2026-09-14    1
Name: count, dtype: int64

In [147]:
df[df['Bonus']==22500].value_counts()

Name    Last Name  Age  Field     Salary    Location   Bonus    DOJ
Unil    Pradhan    46   Graphics  150000.0  Lalitpur   22500.0  2022-01-03    1
Fantus  Maharjan   46   Graphics  90000.0   Jaulakhel  22500.0  2023-07-26    1
Name: count, dtype: int64

In [148]:
# Group By

In [151]:
df.groupby('Bonus')['Salary'].mean()

Bonus
22500.0    120000.000000
25000.0    106833.333333
30000.0    120000.000000
50000.0    200000.000000
Name: Salary, dtype: float64

In [153]:
df.groupby('Location')['Salary'].mean()

Location
Basantapur    120000.0
Bhaktapur     120000.0
Dhulikhel     120500.0
Jaulakhel      90000.0
Kathmandu     100000.0
Lalitpur      150000.0
Panauti       200000.0
Pokhara       200000.0
Sanga         100000.0
Surkhet       120000.0
Name: Salary, dtype: float64

In [154]:
df.groupby('Bonus')['Salary'].sum()

Bonus
22500.0    240000.0
25000.0    320500.0
30000.0    360000.0
50000.0    400000.0
Name: Salary, dtype: float64

In [157]:
df.groupby('Bonus').agg({'Salary':'mean', 'Name': 'count'})

                Salary  Name
Bonus
22500.0  120000.000000     2
25000.0  106833.333333     3
30000.0  120000.000000     3
50000.0  200000.000000     2

In [158]:
# Lesson 10. Concatination and Merge dataframes

In [161]:
df1 = pd.DataFrame({
    'ID':[1,2,3],
    'Name':['A','B','C'],
    'Address':['Add1','Add2','Add3']
})

In [162]:
df1

   ID Name Address
0   1    A    Add1
1   2    B    Add2
2   3    C    Add3

In [163]:
df2 = pd.DataFrame({
    'ID':[1,2,3,4],
    'Score':[77,88,99,66]
})

In [164]:
df2

   ID  Score
0   1     77
1   2     88
2   3     99
3   4     66

In [165]:
pd.concat([df1,df2],axis = 0) # vertical / row level / top on top

   ID Name Address  Score
0   1    A    Add1    NaN
1   2    B    Add2    NaN
2   3    C    Add3    NaN
0   1  NaN     NaN   77.0
1   2  NaN     NaN   88.0
2   3  NaN     NaN   99.0
3   4  NaN     NaN   66.0

In [166]:
pd.concat([df1,df2],axis = 1)  # horizontal / column level / side on side

    ID Name Address  ID  Score
0  1.0    A    Add1   1     77
1  2.0    B    Add2   2     88
2  3.0    C    Add3   3     99
3  NaN  NaN     NaN   4     66

In [167]:
# merge = join
pd.merge(df1,df2, how = 'inner', on ='ID' )

   ID Name Address  Score
0   1    A    Add1     77
1   2    B    Add2     88
2   3    C    Add3     99

In [168]:
pd.merge(df1,df2, how = 'inner', left_on ='ID', right_on ='ID'  )

   ID Name Address  Score
0   1    A    Add1     77
1   2    B    Add2     88
2   3    C    Add3     99

In [ ]:
# Lesson 11. AI and ChatGPT

In [169]:
df

,Name,Last Name,Age,Field,Salary,Location,Bonus,DOJ
0,Anil,Shakya,34,Frontend,100000.0,Kathmandu,25000.0,2022-07-04
1,Sunil,Prajapati,36,UIUX,120000.0,Bhaktapur,30000.0,2024-03-14
2,Pranil,Shrestha,35,Backend,200000.0,Pokhara,50000.0,2023-04-11
3,Unil,Pradhan,46,Graphics,150000.0,Lalitpur,22500.0,2022-01-03
4,Banmboo,Maharjan,34,Data Scientist,100000.0,Sanga,25000.0,2025-11-04
5,Hancy,Shakya,36,UIUX,120000.0,Surkhet,30000.0,2023-11-11
6,Hakim,Pradhan,35,Backend,200000.0,Panauti,50000.0,2026-09-14
7,Fantus,Maharjan,46,Graphics,90000.0,Jaulakhel,22500.0,2023-07-26
8,Binny,Tamang,23,Data Scientist,120500.0,Dhulikhel,25000.0,2023-07-14
9,Prajin,Chetri,43,Graphics,120000.0,Basantapur,30000.0,2022-08-28

In [180]:
# Filter employees
df[(df["DOJ"].dt.month == 3) & (df["Salary"] >= 100000)]

    Name  Last Name  Age Field    Salary   Location    Bonus        DOJ
1  Sunil  Prajapati   36  UIUX  120000.0  Bhaktapur  30000.0 2024-03-14

In [182]:
# Using .query() method
df.query("Salary >= 100000 and DOJ.dt.month == 3")

    Name  Last Name  Age Field    Salary   Location    Bonus        DOJ
1  Sunil  Prajapati   36  UIUX  120000.0  Bhaktapur  30000.0 2024-03-14