In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Name" : ["cat","dog","fish","crocodile","monkey"]
})
df

        Name
0        cat
1        dog
2       fish
3  crocodile
4     monkey

In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder()
df["en_name"] = le.fit_transform(df["Name"])

In [5]:
df

        Name  en_name
0        cat        0
1        dog        2
2       fish        3
3  crocodile        1
4     monkey        4

In [6]:
data = pd.read_csv("loan.csv")

In [7]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [8]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [9]:
# Label Encoding on loan  dataset Education

edu_label = LabelEncoder()
edu_label.fit(data["Education"])

LabelEncoder()

In [10]:
data["Education"]=edu_label.transform(data["Education"])

In [11]:
data["Education"].unique()

array([0, 1])

In [12]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,0,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,0,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,0,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,1,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,0,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,0,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,0,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,0,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,0,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,0,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [13]:
pa_label = LabelEncoder()
pa_label.fit(data["Property_Area"])

LabelEncoder()

In [14]:
data["Property_Area"] = pa_label.transform(data["Property_Area"])

In [15]:
data["Property_Area"]

0      2
1      0
2      2
3      2
4      2
      ..
609    0
610    0
611    2
612    2
613    1
Name: Property_Area, Length: 614, dtype: int64

In [16]:
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,0,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,Male,Yes,1,0,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,Male,Yes,0,0,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,Male,Yes,0,1,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,Male,No,0,0,No,6000,0.0,141.0,360.0,1.0,2,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,0,No,2900,0.0,71.0,360.0,1.0,0,Y
610,LP002979,Male,Yes,3+,0,No,4106,0.0,40.0,180.0,1.0,0,Y
611,LP002983,Male,Yes,1,0,No,8072,240.0,253.0,360.0,1.0,2,Y
612,LP002984,Male,Yes,2,0,No,7583,0.0,187.0,360.0,1.0,2,Y
613,LP002990,Female,No,0,0,Yes,4583,0.0,133.0,360.0,0.0,1,N

In [17]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,0,No,5849,0.0,NaN,360.0,1.0,2,Y
1,LP001003,Male,Yes,1,0,No,4583,1508.0,128.0,360.0,1.0,0,N
2,LP001005,Male,Yes,0,0,Yes,3000,0.0,66.0,360.0,1.0,2,Y
3,LP001006,Male,Yes,0,1,No,2583,2358.0,120.0,360.0,1.0,2,Y
4,LP001008,Male,No,0,0,No,6000,0.0,141.0,360.0,1.0,2,Y

In [18]:
data["Property_Area"].unique()

array([2, 0, 1])

In [ ]:
https://youtu.be/gDZ6czwuQ18
7 12 7