In [ ]:
# UPDATING THE DATAFRAME
people = {
    "firstName": ["Suncha", "sirish","sabin", "mika"],
    "lastName": ["voxx", "dalli", "rai", "dalli"],
    "email": ["Sunchavoxx@gmail.com", "sirishdalli@gmail.com","sabinrai@gmail.com", "mikadalli@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

  firstName lastName                  email
0    Suncha     voxx   Sunchavoxx@gmail.com
1    sirish    dalli  sirishdalli@gmail.com
2     sabin      rai     sabinrai@gmail.com
3      mika    dalli    mikadalli@gmail.com

In [ ]:
df.columns  # Executes the columns name

Index(['firstName', 'lastName', 'email'], dtype='str')

In [ ]:
df.columns = ["first_name", "last_name", "email"]   # changes the columns name

In [7]:
df

  first_name last_name                  email
0     Suncha      voxx   Sunchavoxx@gmail.com
1     sirish     dalli  sirishdalli@gmail.com
2      sabin       rai     sabinrai@gmail.com
3       mika     dalli    mikadalli@gmail.com

In [ ]:
# list comprehension method to change columns name
# columns name into upper case

df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                  EMAIL
0     Suncha      voxx   Sunchavoxx@gmail.com
1     sirish     dalli  sirishdalli@gmail.com
2      sabin       rai     sabinrai@gmail.com
3       mika     dalli    mikadalli@gmail.com

In [ ]:
# list comprehension method to change it in lower case
df.columns = [x.lower() for x in df.columns]

In [10]:
df

  first_name last_name                  email
0     Suncha      voxx   Sunchavoxx@gmail.com
1     sirish     dalli  sirishdalli@gmail.com
2      sabin       rai     sabinrai@gmail.com
3       mika     dalli    mikadalli@gmail.com

In [ ]:
# Changing _ to space or vice-versa 
df.columns = df.columns.str.replace(" ","_")
df

  first_name last_name                  email
0     Suncha      voxx   Sunchavoxx@gmail.com
1     sirish     dalli  sirishdalli@gmail.com
2      sabin       rai     sabinrai@gmail.com
3       mika     dalli    mikadalli@gmail.com

In [ ]:
# rename the columns
df.rename(columns = {"first_name": "first", "last_name": "last"})

    first   last                  email
0  Suncha   voxx   Sunchavoxx@gmail.com
1  sirish  dalli  sirishdalli@gmail.com
2   sabin    rai     sabinrai@gmail.com
3    mika  dalli    mikadalli@gmail.com

In [14]:
df

  first_name last_name                  email
0     Suncha      voxx   Sunchavoxx@gmail.com
1     sirish     dalli  sirishdalli@gmail.com
2      sabin       rai     sabinrai@gmail.com
3       mika     dalli    mikadalli@gmail.com

In [ ]:
# inplace = True just changed it permanently
df.rename(columns = {"first_name": "first", "last_name": "last"}, inplace = True)
df

    first   last                  email
0  Suncha   voxx   Sunchavoxx@gmail.com
1  sirish  dalli  sirishdalli@gmail.com
2   sabin    rai     sabinrai@gmail.com
3    mika  dalli    mikadalli@gmail.com

In [16]:
df.loc[1]

first                   sirish
last                     dalli
email    sirishdalli@gmail.com
Name: 1, dtype: str

In [ ]:
# locating row and updating data
df.loc[2] = ["Sirish", "Mali","sirishmali@gmail.com"]
df

    first   last                  email
0  Suncha   voxx   Sunchavoxx@gmail.com
1  sirish  dalli  sirishdalli@gmail.com
2  Sirish   Mali   sirishmali@gmail.com
3    mika  dalli    mikadalli@gmail.com

In [19]:
df

    first   last                  email
0  Suncha   voxx   Sunchavoxx@gmail.com
1  sirish  dalli  sirishdalli@gmail.com
2  Sirish   Mali   sirishmali@gmail.com
3    mika  dalli    mikadalli@gmail.com

In [ ]:
# locate the row and select the columns name as required
df.loc[1,["last","email"]]

last                     dalli
email    sirishdalli@gmail.com
Name: 1, dtype: str

In [21]:
df

    first   last                  email
0  Suncha   voxx   Sunchavoxx@gmail.com
1  sirish  dalli  sirishdalli@gmail.com
2  Sirish   Mali   sirishmali@gmail.com
3    mika  dalli    mikadalli@gmail.com

In [27]:
df.at[1,"last"] = "Malati"

In [28]:
df

    first    last                  email
0  Suncha    voxx   Sunchavoxx@gmail.com
1  sirish  Malati  sirishdalli@gmail.com
2  Sirish    Mali   sirishmali@gmail.com
3    mika   dalli    mikadalli@gmail.com

In [29]:
df.at[1,"email"] = "sirishmalati@gmail.com"

In [30]:
df

    first    last                   email
0  Suncha    voxx    Sunchavoxx@gmail.com
1  sirish  Malati  sirishmalati@gmail.com
2  Sirish    Mali    sirishmali@gmail.com
3    mika   dalli     mikadalli@gmail.com

In [31]:
filt = (df["email"] == "sirishmalati@gmail.com")
df[filt]

    first    last                   email
1  sirish  Malati  sirishmalati@gmail.com

In [32]:
df

    first    last                   email
0  Suncha    voxx    Sunchavoxx@gmail.com
1  sirish  Malati  sirishmalati@gmail.com
2  Sirish    Mali    sirishmali@gmail.com
3    mika   dalli     mikadalli@gmail.com

In [33]:
df

    first    last                   email
0  Suncha    voxx    Sunchavoxx@gmail.com
1  sirish  Malati  sirishmalati@gmail.com
2  Sirish    Mali    sirishmali@gmail.com
3    mika   dalli     mikadalli@gmail.com

In [34]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [35]:
df.shape

(4, 3)

In [37]:
filt = (df["last"] == "dalli")
df[filt]

  first   last                email
3  mika  dalli  mikadalli@gmail.com

In [38]:
filt = (df["last"] == "dalli") & (df["first"] == "mika")
df[filt]

  first   last                email
3  mika  dalli  mikadalli@gmail.com

In [39]:
df

    first    last                   email
0  Suncha    voxx    Sunchavoxx@gmail.com
1  sirish  Malati  sirishmalati@gmail.com
2  Sirish    Mali    sirishmali@gmail.com
3    mika   dalli     mikadalli@gmail.com