In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('hospitalDataAnalysis.csv')

In [5]:
df

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4
...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [ ]:
df.head()   # head function provides first 5 rows

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4

In [ ]:
df.tail()   # tail function provides last 5 rows

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [ ]:
df.head(3)  # head function with parameter provides first rows

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5

In [ ]:
df.tail(3)  # tail function with parameter provides last rows

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [ ]:
df.info()   # All the information of the dataframe is provided
# RangeIndex: 984 entries, 0 to 983
# Data columns (total 10 columns):
# datatype is also shown

<class 'pandas.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Patient_ID      984 non-null    int64
 1   Age             984 non-null    int64
 2   Gender          984 non-null    str
 3   Condition       984 non-null    str
 4   Procedure       984 non-null    str
 5   Cost            984 non-null    int64
 6   Length_of_Stay  984 non-null    int64
 7   Readmission     984 non-null    str
 8   Outcome         984 non-null    str
 9   Satisfaction    984 non-null    int64
dtypes: int64(5), str(5)
memory usage: 77.0 KB

In [ ]:
df.describe()   # Statistical informations, mean, count, std etc...

        Patient_ID         Age          Cost  Length_of_Stay  Satisfaction
count   984.000000  984.000000    984.000000      984.000000    984.000000
mean    500.329268   53.754065   8367.479675       37.663618      3.598577
std     288.979531   14.941135   7761.990976       19.595805      0.883002
min       1.000000   25.000000    100.000000        1.000000      2.000000
25%     250.750000   45.000000   1000.000000       21.000000      3.000000
50%     500.500000   55.000000   6000.000000       38.000000      4.000000
75%     750.250000   65.000000  15000.000000       54.250000      4.000000
max    1000.000000   78.000000  25000.000000       76.000000      5.000000

In [ ]:
df.index    # idexes that started from is shown i.e RangeIndex(start=0, stop=984, step=1)

RangeIndex(start=0, stop=984, step=1)

In [24]:
df.columns

Index(['Patient_ID', 'Age', 'Gender', 'Condition', 'Procedure', 'Cost',
       'Length_of_Stay', 'Readmission', 'Outcome', 'Satisfaction'],
      dtype='str')

In [ ]:
df['Condition'] # values that are present inside of Condition column

0          Heart Disease
1               Diabetes
2          Fractured Arm
3                 Stroke
4                 Cancer
             ...
979         Hypertension
980         Appendicitis
981        Fractured Leg
982         Heart Attack
983    Allergic Reaction
Name: Condition, Length: 984, dtype: str

In [ ]:
df[['Condition','Procedure']]   # values that are present inside of Condition Column and Procedure Column

             Condition                  Procedure
0        Heart Disease                Angioplasty
1             Diabetes            Insulin Therapy
2        Fractured Arm           X-Ray and Splint
3               Stroke     CT Scan and Medication
4               Cancer   Surgery and Chemotherapy
..                 ...                        ...
979       Hypertension  Medication and Counseling
980       Appendicitis               Appendectomy
981      Fractured Leg  Cast and Physical Therapy
982       Heart Attack    Cardiac Catheterization
983  Allergic Reaction      Epinephrine Injection

[984 rows x 2 columns]

In [ ]:
len(df["Condition"] )   # shows how many values are located in the COndition column

984

In [ ]:
df.iloc[0] # iloc - Index Location of 0th row full information is. provided

Patient_ID                    1
Age                          45
Gender                   Female
Condition         Heart Disease
Procedure           Angioplasty
Cost                      15000
Length_of_Stay                5
Readmission                  No
Outcome               Recovered
Satisfaction                  4
Name: 0, dtype: object

In [ ]:
df.iloc[5]["Condition"] # iloc - Index Location of 5th index condition is provided

'Hypertension'

In [ ]:
df.iloc[1:4]    # iloc - Index Location of 1 to 3rd index rows are provided

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2

In [33]:
# Filters
df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4

In [ ]:
df[df["Condition"] == "Fractured Arm"] # Filters the specific datas only
# Only Fractured Arm is shown

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
17,18,35,Female,Fractured Arm,X-Ray and Splint,500,2,Yes,Recovered,5
32,33,30,Female,Fractured Arm,X-Ray and Splint,500,3,No,Recovered,5
47,48,35,Female,Fractured Arm,X-Ray and Splint,500,4,Yes,Recovered,5
61,63,30,Female,Fractured Arm,X-Ray and Splint,500,5,No,Recovered,5
...,...,...,...,...,...,...,...,...,...,...
917,933,30,Female,Fractured Arm,X-Ray and Splint,500,63,No,Recovered,5
932,948,35,Female,Fractured Arm,X-Ray and Splint,500,64,Yes,Recovered,5
947,963,30,Female,Fractured Arm,X-Ray and Splint,500,65,No,Recovered,5
961,978,35,Female,Fractured Arm,X-Ray and Splint,500,66,Yes,Recovered,5
976,993,30,Female,Fractured Arm,X-Ray and Splint,500,67,No,Recovered,5

In [35]:
df[(df["Condition"] == "Fractured Arm") & (df["Age"] == 35)]

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
17,18,35,Female,Fractured Arm,X-Ray and Splint,500,2,Yes,Recovered,5
47,48,35,Female,Fractured Arm,X-Ray and Splint,500,4,Yes,Recovered,5
76,78,35,Female,Fractured Arm,X-Ray and Splint,500,6,Yes,Recovered,5
106,108,35,Female,Fractured Arm,X-Ray and Splint,500,8,Yes,Recovered,5
135,138,35,Female,Fractured Arm,X-Ray and Splint,500,10,Yes,Recovered,5
165,168,35,Female,Fractured Arm,X-Ray and Splint,500,12,Yes,Recovered,5
194,198,35,Female,Fractured Arm,X-Ray and Splint,500,14,Yes,Recovered,5
224,228,35,Female,Fractured Arm,X-Ray and Splint,500,16,Yes,Recovered,5
253,258,35,Female,Fractured Arm,X-Ray and Splint,500,18,Yes,Recovered,5
283,288,35,Female,Fractured Arm,X-Ray and Splint,500,20,Yes,Recovered,5
312,318,35,Female,Fractured Arm,X-Ray and Splint,500,22,Yes,Recovered,5
342,348,35,Female,Fractured Arm,X-Ray and Splint,500,24,Yes,Recovered,5
371,378,35,Female,Fractured Arm,X-Ray and Splint,500,26,Yes,Recovered,5
401,408,35,Female,Fractured Arm,X-Ray and Splint,500,28,Yes,Recovered,5
430,438,35,Female,Fractured Arm,X-Ray and Splint,500,30,Yes,Recovered,5
460,468,35,Female,Fractured Arm,X-Ray and Splint,500,32,Yes,Recovered,5
489,498,35,Female,Fractured Arm,X-Ray and Splint,500,34,Yes,Recovered,5
519,528,35,Female,Fractured Arm,X-Ray and Splint,500,36,Yes,Recovered,5
548,558,35,Female,Fractured Arm,X-Ray and Splint,500,38,Yes,Recovered,5
578,588,35,Female,Fractured Arm,X-Ray and Splint,500,40,Yes,Recovered,5
607,618,35,Female,Fractured Arm,X-Ray and Splint,500,42,Yes,Recovered,5
637,648,35,Female,Fractured Arm,X-Ray and Splint,500,44,Yes,Recovered,5
666,678,35,Female,Fractured Arm,X-Ray and Splint,500,46,Yes,Recovered,5
696,708,35,Female,Fractured Arm,X-Ray and Splint,500,48,Yes,Recovered,5
725,738,35,Female,Fractured Arm,X-Ray and Splint,500,50,Yes,Recovered,5
755,768,35,Female,Fractured Arm,X-Ray and Splint,500,52,Yes,Recovered,5
784,798,35,Female,Fractured Arm,X-Ray and Splint,500,54,Yes,Recovered,5
814,828,35,Female,Fractured Arm,X-Ray and Splint,500,56,Yes,Recovered,5
843,858,35,Female,Fractured Arm,X-Ray and Splint,500,58,Yes,Recovered,5
873,888,35,Female,Fractured Arm,X-Ray and Splint,500,60,Yes,Recovered,5
902,918,35,Female,Fractured Arm,X-Ray and Splint,500,62,Yes,Recovered,5
932,948,35,Female,Fractured Arm,X-Ray and Splint,500,64,Yes,Recovered,5
961,978,35,Female,Fractured Arm,X-Ray and Splint,500,66,Yes,Recovered,5

In [ ]:
# Total number of people whose COndition was Fractured Arm and of aged 35
len(df[(df["Condition"] == "Fractured Arm") & (df["Age"] == 35)])
# Ther were 33 people who were have Fractured Arm and of 35 years old

33

In [37]:
len(df[df["Condition"] == "Headach"])

0

In [38]:
df["Condition"]

0          Heart Disease
1               Diabetes
2          Fractured Arm
3                 Stroke
4                 Cancer
             ...
979         Hypertension
980         Appendicitis
981        Fractured Leg
982         Heart Attack
983    Allergic Reaction
Name: Condition, Length: 984, dtype: str

In [41]:
df[df["Condition"] == "Diabetes"]

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
16,17,62,Male,Diabetes,Insulin Therapy,2000,4,No,Stable,4
31,32,65,Male,Diabetes,Insulin Therapy,2000,5,No,Stable,3
46,47,62,Male,Diabetes,Insulin Therapy,2000,6,No,Stable,4
60,62,65,Male,Diabetes,Insulin Therapy,2000,7,No,Stable,3
...,...,...,...,...,...,...,...,...,...,...
916,932,65,Male,Diabetes,Insulin Therapy,2000,65,No,Stable,3
931,947,62,Male,Diabetes,Insulin Therapy,2000,66,No,Stable,4
946,962,65,Male,Diabetes,Insulin Therapy,2000,67,No,Stable,3
960,977,62,Male,Diabetes,Insulin Therapy,2000,68,No,Stable,4
975,992,65,Male,Diabetes,Insulin Therapy,2000,69,No,Stable,3

In [42]:
len(df[df["Condition"] == "Diabetes"])

65

In [61]:
# len(df[(df["Condition"] == "Diabetes"]) & (df["Procedure"] == "Therapy"))

len(df[(df["Condition"] == "Diabetes") | (df["Satisfaction"] == 3)]) # OR operator (|)

294

In [62]:
df.head()

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4

In [ ]:
df[df["Cost"] > 20000] # Greater than operator >

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4
19,20,53,Female,Cancer,Surgery and Chemotherapy,25000,11,Yes,Recovered,4
34,35,55,Female,Cancer,Surgery and Chemotherapy,25000,12,No,Recovered,4
49,50,53,Female,Cancer,Surgery and Chemotherapy,25000,13,Yes,Recovered,4
63,65,55,Female,Cancer,Surgery and Chemotherapy,25000,14,No,Recovered,4
...,...,...,...,...,...,...,...,...,...,...
919,935,55,Female,Cancer,Surgery and Chemotherapy,25000,72,No,Recovered,4
934,950,53,Female,Cancer,Surgery and Chemotherapy,25000,73,Yes,Recovered,4
949,965,55,Female,Cancer,Surgery and Chemotherapy,25000,74,No,Recovered,4
963,980,53,Female,Cancer,Surgery and Chemotherapy,25000,75,Yes,Recovered,4
978,995,55,Female,Cancer,Surgery and Chemotherapy,25000,76,No,Recovered,4

In [76]:
len(df[df["Cost"] > 20000])

66

In [77]:
df[df["Condition"].str.startswith("A")]

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
6,7,55,Female,Appendicitis,Appendectomy,8000,4,No,Recovered,3
9,10,25,Male,Allergic Reaction,Epinephrine Injection,100,1,No,Recovered,5
21,22,60,Female,Appendicitis,Appendectomy,8000,5,Yes,Recovered,3
24,25,28,Male,Allergic Reaction,Epinephrine Injection,100,2,No,Recovered,5
36,37,45,Female,Appendicitis,Appendectomy,8000,6,No,Recovered,3
...,...,...,...,...,...,...,...,...,...,...
953,970,25,Male,Allergic Reaction,Epinephrine Injection,100,65,No,Recovered,5
965,982,60,Female,Appendicitis,Appendectomy,8000,71,Yes,Recovered,3
968,985,28,Male,Allergic Reaction,Epinephrine Injection,100,67,No,Recovered,5
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [78]:
df[df["Condition"].str.startswith("A")]

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
6,7,55,Female,Appendicitis,Appendectomy,8000,4,No,Recovered,3
9,10,25,Male,Allergic Reaction,Epinephrine Injection,100,1,No,Recovered,5
21,22,60,Female,Appendicitis,Appendectomy,8000,5,Yes,Recovered,3
24,25,28,Male,Allergic Reaction,Epinephrine Injection,100,2,No,Recovered,5
36,37,45,Female,Appendicitis,Appendectomy,8000,6,No,Recovered,3
...,...,...,...,...,...,...,...,...,...,...
953,970,25,Male,Allergic Reaction,Epinephrine Injection,100,65,No,Recovered,5
965,982,60,Female,Appendicitis,Appendectomy,8000,71,Yes,Recovered,3
968,985,28,Male,Allergic Reaction,Epinephrine Injection,100,67,No,Recovered,5
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [83]:
df[(df["Condition"].str.startswith("A")) & (df["Condition"].str.endswith("s"))]

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
6,7,55,Female,Appendicitis,Appendectomy,8000,4,No,Recovered,3
21,22,60,Female,Appendicitis,Appendectomy,8000,5,Yes,Recovered,3
36,37,45,Female,Appendicitis,Appendectomy,8000,6,No,Recovered,3
51,52,60,Female,Appendicitis,Appendectomy,8000,7,Yes,Recovered,3
65,67,45,Female,Appendicitis,Appendectomy,8000,8,No,Recovered,3
...,...,...,...,...,...,...,...,...,...,...
906,922,60,Female,Appendicitis,Appendectomy,8000,67,Yes,Recovered,3
921,937,45,Female,Appendicitis,Appendectomy,8000,68,No,Recovered,3
936,952,60,Female,Appendicitis,Appendectomy,8000,69,Yes,Recovered,3
965,982,60,Female,Appendicitis,Appendectomy,8000,71,Yes,Recovered,3
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3

In [ ]:
df[df["Condition"].isin(["Diabetes","Appendicitis","Allergic Reaction"])]   # isin operator

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
6,7,55,Female,Appendicitis,Appendectomy,8000,4,No,Recovered,3
9,10,25,Male,Allergic Reaction,Epinephrine Injection,100,1,No,Recovered,5
16,17,62,Male,Diabetes,Insulin Therapy,2000,4,No,Stable,4
21,22,60,Female,Appendicitis,Appendectomy,8000,5,Yes,Recovered,3
...,...,...,...,...,...,...,...,...,...,...
965,982,60,Female,Appendicitis,Appendectomy,8000,71,Yes,Recovered,3
968,985,28,Male,Allergic Reaction,Epinephrine Injection,100,67,No,Recovered,5
975,992,65,Male,Diabetes,Insulin Therapy,2000,69,No,Stable,3
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [91]:
df[~df["Procedure"].isin(["Angioplasty","X-Ray and Splint","Medication and Counseling","Surgery and Chemotherapy"])]   # ~isin operator

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
6,7,55,Female,Appendicitis,Appendectomy,8000,4,No,Recovered,3
7,8,40,Male,Fractured Leg,Cast and Physical Therapy,3000,6,No,Recovered,4
8,9,70,Female,Heart Attack,Cardiac Catheterization,18000,8,Yes,Stable,2
...,...,...,...,...,...,...,...,...,...,...
977,994,70,Male,Stroke,CT Scan and Medication,10000,74,Yes,Stable,2
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [92]:
# Updating Data

In [99]:
df.loc[4]   # loc - locate accessing 4th data

Patient_ID                               5
Age                                     50
Gender                              Female
Condition                           Cancer
Procedure         Surgery and Chemotherapy
Cost                                 25000
Length_of_Stay                          10
Readmission                             No
Outcome                          Recovered
Satisfaction                             4
Product                                NaN
Name: 4, dtype: object

In [103]:
df.loc[df["Condition"] == "Diabetes", "Fee"] = "Fee"

In [107]:
df.drop("Product", axis=1)

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction,Fee
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4,NaN
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3,Fee
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5,NaN
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2,NaN
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4,NaN
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3,NaN
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4,NaN
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2,NaN
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5,NaN

In [109]:
df.drop("Fee", axis=1, inplace=True)

In [110]:
df

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction,Product
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4,NaN
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3,FEVER
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5,NaN
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2,NaN
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4,NaN
...,...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4,NaN
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3,NaN
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4,NaN
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2,NaN
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5,NaN

In [ ]:
# Delete
df.drop("Product", axis=1, inplace=True)

In [112]:
df

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,Recovered,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,Stable,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,Recovered,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,Stable,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,Recovered,4
...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,Stable,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,Recovered,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,Recovered,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,Stable,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,Recovered,5

In [ ]:
df["Outcome"] = df["Outcome"].str.upper()   # str.upper() method changes entire column into upper case

In [114]:
df["Outcome"]

0      RECOVERED
1         STABLE
2      RECOVERED
3         STABLE
4      RECOVERED
         ...
979       STABLE
980    RECOVERED
981    RECOVERED
982       STABLE
983    RECOVERED
Name: Outcome, Length: 984, dtype: str

In [115]:
df

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,RECOVERED,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,STABLE,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,RECOVERED,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,STABLE,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,RECOVERED,4
...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,STABLE,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,RECOVERED,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,RECOVERED,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,STABLE,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,RECOVERED,5

In [116]:
df.dropna()

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
0,1,45,Female,Heart Disease,Angioplasty,15000,5,No,RECOVERED,4
1,2,60,Male,Diabetes,Insulin Therapy,2000,3,Yes,STABLE,3
2,3,32,Female,Fractured Arm,X-Ray and Splint,500,1,No,RECOVERED,5
3,4,75,Male,Stroke,CT Scan and Medication,10000,7,Yes,STABLE,2
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,RECOVERED,4
...,...,...,...,...,...,...,...,...,...,...
979,996,68,Male,Hypertension,Medication and Counseling,1000,70,No,STABLE,4
980,997,45,Female,Appendicitis,Appendectomy,8000,72,No,RECOVERED,3
981,998,40,Male,Fractured Leg,Cast and Physical Therapy,3000,72,No,RECOVERED,4
982,999,78,Female,Heart Attack,Cardiac Catheterization,18000,74,Yes,STABLE,2
983,1000,25,Male,Allergic Reaction,Epinephrine Injection,100,68,No,RECOVERED,5

In [ ]:
df["Condition"].value_counts()  # value_counts() method counts entire number data of the column

Condition
Fractured Leg            67
Heart Attack             67
Fractured Arm            66
Stroke                   66
Cancer                   66
Hypertension             66
Appendicitis             66
Allergic Reaction        66
Heart Disease            65
Diabetes                 65
Respiratory Infection    65
Prostate Cancer          65
Childbirth               65
Kidney Stones            65
Osteoarthritis           64
Name: count, dtype: int64

In [118]:
df.groupby("Condition")["Cost"].sum()

Condition
Allergic Reaction           6600
Appendicitis              528000
Cancer                   1650000
Childbirth                780000
Diabetes                  130000
Fractured Arm              33000
Fractured Leg             201000
Heart Attack             1206000
Heart Disease             975000
Hypertension               66000
Kidney Stones             390000
Osteoarthritis            256000
Prostate Cancer          1300000
Respiratory Infection      52000
Stroke                    660000
Name: Cost, dtype: int64

In [119]:
df.sort_values("Cost", ascending=False)

,Patient_ID,Age,Gender,Condition,Procedure,Cost,Length_of_Stay,Readmission,Outcome,Satisfaction
949,965,55,Female,Cancer,Surgery and Chemotherapy,25000,74,No,RECOVERED,4
4,5,50,Female,Cancer,Surgery and Chemotherapy,25000,10,No,RECOVERED,4
358,365,55,Female,Cancer,Surgery and Chemotherapy,25000,34,No,RECOVERED,4
211,215,55,Female,Cancer,Surgery and Chemotherapy,25000,24,No,RECOVERED,4
934,950,53,Female,Cancer,Surgery and Chemotherapy,25000,73,Yes,RECOVERED,4
...,...,...,...,...,...,...,...,...,...,...
658,670,25,Male,Allergic Reaction,Epinephrine Injection,100,45,No,RECOVERED,5
39,40,25,Male,Allergic Reaction,Epinephrine Injection,100,3,No,RECOVERED,5
349,355,28,Male,Allergic Reaction,Epinephrine Injection,100,24,No,RECOVERED,5
24,25,28,Male,Allergic Reaction,Epinephrine Injection,100,2,No,RECOVERED,5
9,10,25,Male,Allergic Reaction,Epinephrine Injection,100,1,No,RECOVERED,5

In [120]:
df.to_csv("New_hospital.csv", index= False)